# Generated by Django 4.0.2 on 2022-02-22 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='')),
                ('value', models.CharField(max_length=150, verbose_name='value of type')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of filter')),
                ('description', models.TextField(verbose_name='a full description for filter')),
                ('price', models.PositiveIntegerField(verbose_name='price of a filter')),
                ('rank', models.CharField(blank=True, max_length=3, null=True, verbose_name='rank of filter')),
            ],
        ),
        migrations.CreateModel(
            name='Permium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('G', 'G'), ('S', 'S'), ('B', 'B')], max_length=1, verbose_name='type of permium account')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateField(verbose_name='after active a permium account its end in 3 month')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(verbose_name='its must from 0 to 5')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='accounts.filter', verbose_name='belong to a filter')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='mac_address',
            field=models.CharField(default=1, max_length=120, verbose_name='a unique address of every device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=32, verbose_name='family name'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='rank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='what user give this rate'),
        ),
        migrations.AddField(
            model_name='permium',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='permium', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.filter', verbose_name='belong to a filter'),
        ),
    ]
